# Generated by Django 4.2 on 2023-11-06 22:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_publish_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date',
        ),
    ]
