# Generated by Django 4.2 on 2023-11-07 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_post_publish_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date2',
        ),
    ]
