# Generated by Django 4.2 on 2023-11-07 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0010_post_publish_date2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='publish_date2',
        ),
        migrations.AlterField(
            model_name='post',
            name='publish_date',
            field=models.DateField(),
        ),
    ]
